### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by rjm521** [firmanjml/Asus-X556UQK-Hackintosh-OC#1]
Thanks for your EFI, it works very well for my laptop. There is only one big issue don't fit me. My Wireless Card is Qualcomm Atheros 9565 but i can't find a proper kext to let it work. Do you have any ideas about this problem? 
One more thing, as your picture shows, its vram don't fit very well, it shows 1536m, ususally it should be 2048m.

**Comment by firmanjml** [comment]
Hi @rjm521,

I’m glad that it works on your device too! 👍
As for your wifi card, have you tried ATH9KFIXUP kext?
Based on the recent update, I don’t think it works on Big Sur

And about the VRAM? Thanks for informing me of the issue and I will look into it.

** EDIT
I have done some research based on the VRAM issue you've stated and came to conclude that 1536 to 1537MB is the normal range on MacOS, probably because of the SMBios I picked?.

**Comment by rjm521** [comment]
I got it.
